(function(g){var window=this;'use strict';var z4=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},A4=function(a){return g.lE(a)&&a.L("web_player_i_see_captions_3")},aWa=function(a,b){var c,d,e;
return g.B(function(f){if(1==f.i)return c=a+"|"+b,g.A(f,g.Pv(),2);if(3!=f.i){d=f.j;if(!d)throw g.nv("gct");return g.A(f,g.OE(d),3)}e=f.j;return f.return(e.get("captions",c))})},bWa=function(a,b){var c=new g.RE;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},cWa=function(a,b,c){aWa(a,b).then(function(d){d&&c(d.trackData,new g.RE(d.metadata))})},B4=function(){this.segments=[]},dWa=function(a,b){var c=g.sc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.fc(a.segments,c),g.fc(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.pc(a.segments,c,0,b),g.pc(a.segments,c+1,0,b)))},C4=function(a,b,c,d,e,f){g.H.call(this);
this.policy=a;this.player=b;this.Y=c;this.N=d;this.C=e;this.W=f;this.X=this.player.T();this.B=new B4;this.I=-1;this.u=this.j=this.i=null;this.J=new g.K(this.MM,1E3,this);this.events=new g.hC(this);g.J(this,this.J);g.J(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.YA);this.YA();this.MM()},eWa=function(a){return a.i&&a.i.C?a.i.C+a.player.jd()<a.player.getCurrentTime():!1},fWa=function(a,b){var c=g.bB(g.xB(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Xs(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.j){var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.gra(e);if(h){e=g.xB(a.j,a.policy,{});a.j.Gj(e,h);fWa(a,a.j);break a}f?a.player.Aa("capfail",{status:e.status}):(h=a.j.i[0].Na,null!=a.N&&a.I!==h&&(f=a.j.i[0],a.C?a.N(e.response,1E3*(f.startTime+a.player.jd())):a.N(e.responseText,1E3*(f.startTime+a.player.jd())),a.I=h))}a.j=null;a.u=null}}).wh(function(e){var f;
a.j=null;a.u=null;a.player.Aa("capfail",{status:null===(f=e.xhr)||void 0===f?void 0:f.status});a.ra()});
a.j=b;dWa(a.B,a.j.i[0].Na)},D4=function(a,b){g.rM.call(this,b.T());
this.i=a;this.G=b;this.u=null;this.C=!1;this.I=g.nE(this.G.T())&&!this.i.isManifestless},hWa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.tM(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.iUa.get(e);null==n&&(n=gWa[e]||gWa[e.replace(/-/g,"_")],g.iUa.set(e,n));h=n||h}c.push(new g.RE({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},iWa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},jWa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.tM(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},E4=function(a){if(!kWa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(lWa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},F4=function(a,b,c,d,e,f){var h={};
Object.assign(h,b);Object.assign(h,a.params);Object.assign(h,c);var l={};Object.assign(l,b.zd);a.params.zd&&Object.assign(l,a.params.zd);Object.assign(l,c.zd);h.zd=l;g.W.call(this,{D:"div",K:"caption-window",V:{id:"caption-window-"+a.id,dir:1===h.Nf?"rtl":"ltr",tabindex:"0",lang:h.lang},U:[{D:"span",K:"captions-text",V:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.qa=!1;this.j=a;this.ya=this.xa=null;this.playerWidth=e;this.playerHeight=f;this.I=null;this.maxWidth=.96*e;this.Ta=.96*
f;this.i=h;this.zb=c;this.Ha=b;this.B=this.Da("captions-text");this.kb=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Ia=d/360*16;this.type=0;this.Wa=this.Ia*mWa(l);a=new g.Sw(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.pR,this);a.subscribe("dragmove",this.oR,this);a.subscribe("dragend",this.nR,this);this.fb=this.Ya=0;b="";this.i.windowOpacity&&(a=E4(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+
","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":nWa[this.i.textAlign]};this.kb&&(a["border-radius"]=b?this.Wa/8+"px":"");if(this.u=2===this.j.params.Nf||3===this.j.params.Nf)b=this.element,c="vertical-rl",1===this.i.NH&&(c="vertical-lr"),g.Oc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.cn(b,"-o-writing-mode",c),g.cn(b,"-webkit-writing-mode",c),g.cn(b,"writing-mode",c),g.cn(b,"text-orientation","upright"),g.N(b,"ytp-vertical-caption"),3===this.j.params.Nf&&
(g.cn(b,"text-orientation",""),g.cn(b,"transform","rotate(180deg)"));g.cn(this.element,a);switch(this.i.ri){case 0:case 1:case 2:g.N(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.N(this.element,"ytp-caption-window-bottom")}},mWa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},oWa=function(a,b){var c={},d=b.background?b.background:a.i.zd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.zd.backgroundOpacity;d=E4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.kb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ia*mWa(b)+"px";d=1;e=b.color||a.i.zd.color;if(b.color||null!=b.textOpacity)e=E4(e),d=null==b.textOpacity?a.i.zd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.aE&&(h=e=b.aE);var l=a.Ia/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ot()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.zd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ij&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.aU&&(c.visibility="hidden");1===b.dM&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.rE||g.lv,3===a.j.params.Nf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.bk||2===b.bk||3===b.bk||4===b.bk||5===b.bk)if(g.rE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.bk){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},pWa=function(a){a.I=g.Qh("SPAN");
g.cn(a.I,{display:"block"});g.N(a.I,"caption-visual-line");a.B.appendChild(a.I)},qWa=function(a,b){var c=g.Qh("SPAN");
g.cn(c,{display:"inline-block","white-space":"pre-wrap"});g.cn(c,oWa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.cn(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.cn(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},rWa=function(a,b,c){a.qa=a.qa||!!c;
var d={};Object.assign(d,a.i.zd);Object.assign(d,c||b.i);Object.assign(d,a.zb.zd);(c=!a.I)&&pWa(a);for(var e=a.xa&&a.ya&&g.Gf(d,a.ya)?a.xa:qWa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(pWa(a),e=qWa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Rh(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.rE||!g.en(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.en(n.children[2],"text-emphasis-position")&&(m=
a.u?"padding-left":"padding-bottom"),g.jf?g.cn(e,m,"1em"):g.cn(e,m,"0.5em")))}a.ya=d;a.xa=e;a.C.push(b)},G4=function(a,b,c,d){g.rM.call(this,a);
this.videoData=b;this.audioTrack=c;this.Sa=d;this.B=b.YD},H4=function(a,b,c,d,e,f,h){F4.call(this,a,b,c,d,e,f,h);
this.type=1},I4=function(a,b,c,d,e,f,h){F4.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.W=this.N=this.La=0;this.Y=NaN;this.jb=0;this.ub=null;this.Qa=new g.K(this.YW,433,this);g.N(this.element,"ytp-caption-window-rollup");g.J(this,this.Qa);g.cn(this.element,"overflow","hidden")},sWa=function(a,b){if(!b)return"";
a.u&&1!==a.j.params.NH&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},tWa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.j.params.Rm,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.N=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Dn)?(e=g.Qh("SPAN"),g.Xh(e,"\u2013".repeat(d)),g.cn(e,oWa(a,a.i.zd)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.W=c.call(b,a.Y,a.jb,(a.u?d.offsetHeight:d.offsetWidth)+1)},uWa=function(a,b){tWa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.La){var d=0<c&&0===a.La;b||isNaN(c)||d||(g.N(a.element,"ytp-rollup-mode"),g.iq(a.Qa));g.cn(a.B,"transform",sWa(a,c));a.La=c}tWa(a)},J4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.ey.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},K4=function(a,b,c,d,e){g.ey.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},vWa=function(a){var b="_"+L4++;
return new K4(0,0x8000000000000,0,b,a)},xWa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.pe){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=wWa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new J4(a,b,e,c,l,d,m)}switch(m.pe){case 9:case 10:m.bk=1;break;case 11:m.bk=2;break;case 12:m.bk=3;break;case 13:m.bk=4;break;case 14:m.bk=5}return new J4(a,b,e,c,l.textContent||"",d,m)},wWa=function(a,b,c,d,e){var f=g.ot(),h=
f?g.Qh("DIV"):g.Qh("RUBY"),l=g.Qh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Qh("DIV"):g.Qh("RP");a.textContent=b;h.appendChild(a);b=f?g.Qh("DIV"):g.Qh("RT");b.textContent=c;h.appendChild(b);c=e.pe;if(10===c||11===c||12===c||13===c||14===c)if(g.cn(b,"text-emphasis-style","filled circle"),g.cn(b,"text-emphasis-color","currentcolor"),g.cn(b,"webkit-text-emphasis","filled circle"),11===e.pe||13===e.pe)g.cn(b,"webkit-text-emphasis-position","under left"),g.cn(b,"text-emphasis-position","under left");c=!0;if(4===e.pe||7===e.pe||12===e.pe||
14===e.pe)g.cn(h,"ruby-position","over"),g.cn(h,"-webkit-ruby-position","before");else if(5===e.pe||6===e.pe||11===e.pe||13===e.pe)g.cn(h,"ruby-position","under"),g.cn(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Qh("DIV"):g.Qh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.cn(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.cn(f,"display","none"),f=f.nextElementSibling,g.cn(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.cn(h.lastElementChild,"display","none"),d?(g.cn(h,"padding-top","0.6em"),g.cn(f,"top","0")):(g.cn(h,"padding-bottom","0.6em"),g.cn(f,"bottom","0")));return h},M4=function(){g.H.apply(this,arguments)},N4=function(a){M4.call(this);
this.B=a;this.pens={};this.N={};this.W={};this.C="_"+L4++;this.J={};this.u=this.i=null;this.I=!0},O4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},P4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},Q4=function(a,b){a=O4(a,b);
return void 0!==a?a:null},S4=function(a,b){a=a.getAttribute(b);
if(null!=a)return R4.test(a),a},yWa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.W[d]:a.B);a=Q4(b,"mh");null!=a&&(c.Et=a);a=Q4(b,"ju");null!=a&&(c.textAlign=a);a=Q4(b,"pd");null!=a&&(c.Nf=a);a=Q4(b,"sd");null!=a&&(c.NH=a);a=S4(b,"wfc");null!=a&&(c.windowColor=a);b=O4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},zWa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=Q4(b,"ap");null!=a&&(c.ri=a);a=O4(b,"cc");null!=a&&(c.Dn=a);a=O4(b,"ah");null!=a&&(c.jh=a);a=O4(b,"rc");null!=a&&(c.Rm=a);b=O4(b,"av");null!=b&&(c.dk=b);return c},AWa=function(a,b,c,d){var e={};
Object.assign(e,zWa(a,b));Object.assign(e,yWa(a,b));d?g.Gf(e,a.B)?(d=a.C,e=a.B):d="_"+L4++:d=b.getAttribute("id")||"_"+L4++;a=O4(b,"t")+c;b=O4(b,"d")||0x8000000000000;if(2===e.Nf||3===e.Nf)c=e.Rm,e.Rm=e.Dn,e.Dn=c;return new K4(a,b,0,d,e)},T4=function(a){M4.call(this);
this.I=a;this.i=new Map;this.B=new Map;this.C=new Map;this.u=new Map},U4=function(a){a=g.dh(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},BWa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Rm=a);b=b.ccColCount;void 0!==b&&(f.Dn=b);if(2===f.Nf||3===f.Nf)b=f.Rm,f.Rm=f.Dn,f.Dn=b;return new K4(c,d,0,e,f)},W4=function(){this.u=this.time=this.mode=this.j=0;
this.B=new V4(this);this.C=new V4(this);this.i=[];this.clear()},DWa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Mp:a,
zn:b,result:0};a=CWa[a];b=CWa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.zn===d;if(d)return{Mp:a,zn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Mp:a,zn:b,result:2};return{Mp:a,zn:b,result:3}},FWa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.j.clear(),a.C.j.clear()):(a.u=0,EWa(a.B,b,c,d))},GWa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?FWa(a,d.FK,d.GK,b):1===d.type&&a.j&496&&EWa(a.C,d.FK,d.GK,b);a.i.length=0},X4=function(){this.type=0},Y4=function(){this.state=this.zn=this.Mp=0},HWa=function(){this.timestamp=this.i=0},Z4=function(a){this.C=a;
this.u=[];this.i=this.j=this.row=0;this.style=new X4;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new HWa}},$4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},MWa=function(a,b){switch(a){case 0:return IWa[(b&127)-32];
case 1:return JWa[b&15];case 2:return KWa[b&31];case 3:return LWa[b&31]}return 0},a5=function(a){return a.u[a.row][a.j]},b5=function(a,b,c){2<=b&&1<a.j&&(--a.j,a5(a).i=0);
var d=a5(a);d.timestamp=a.C.time+0;d.i=MWa(b,c);32>a.j&&a.j++},NWa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},c5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},d5=function(a){a.row=0<a.i?a.i:1;
a.j=1;c5(a,0,15)},e5=function(a){this.u=a;
this.C=0;this.style=new X4;this.I=new Z4(this.u);this.J=new Z4(this.u);this.text=new Z4(this.u);this.j=this.I;this.B=this.J;this.i=this.j},f5=function(a,b,c){var d=a.j,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||($4(d,c),d5(a.j),d5(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.j=1:d.i!==b&&(d.i>b?($4(d,c),c5(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},OWa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},PWa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},V4=function(a){this.i=a;
this.C=0;this.u=new e5(this.i);this.I=new e5(this.i);this.j=new Y4;this.B=this.u},EWa=function(a,b,c,d){a.j.update();
b=DWa(b,c,a.j);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Mp;c=b.zn;if(32<=e||!e)a.i.mode&a.i.j&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&b5(a,0,b),c&96&&b5(a,0,c),0!==b&&0!==c&&3===a.style.type&&$4(a,d));else if(e&16)a:if(!a.j.matches(e,c)&&(b=a.j,b.Mp=e,b.zn=c,b.state=2,b=e&8?a.I:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.j))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;NWa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));c5(c,b,e)}}c.row=d;c.j=a+1}else switch(e&7){case 1:switch(c&112){case 32:b5(b.i,0,32);break a;case 48:57===c?(d=b.i,a5(d).i=0,32>d.j&&d.j++):b5(b.i,1,c&15)}break;case 2:c&32&&b5(b.i,2,c&31);break;case 3:c&32&&b5(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:OWa(b);
break;case 33:d=b.i;1<d.j&&(--d.j,a5(d).i=0);break;case 36:d=b.i;b=a5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:f5(b,2,d);break;case 38:f5(b,3,d);break;case 39:f5(b,4,d);break;case 40:b5(b.i,0,32);break;case 41:b.style.set(2);b.i=b.j;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);d5(d);PWa(b);break;case 43:PWa(b);break;case 44:a=b.j;switch(b.style.get()){case 1:case 2:case 3:$4(a,d)}c5(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.j=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;$4(a,d);NWa(a,b,b+1,a.i-1);c5(a,a.row,1)}break;case 46:c5(b.B,0,15);break;case 47:$4(b.j,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.j,b.j=d,OWa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.j+=c&3)&&(d.j=32)}}},QWa=function(){},g5=function(a,b,c){this.trackData=a;
this.J=c;this.version=this.I=this.B=this.i=0;this.j=new DataView(this.trackData);this.u=[]},h5=function(a){var b=a.i;
a.i+=1;return a.j.getUint8(b)},i5=function(a){var b=a.i;
a.i+=4;return a.j.getUint32(b)},j5=function(a,b){M4.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new W4;this.i.j=1<<this.track},k5=function(a){if("string"===typeof a)return!1;
a=new g5(a,8,0);return RWa(a)},RWa=function(a){if(!(a.i<a.j.byteLength)||1380139777!==i5(a))return!1;
a.version=h5(a);if(1<a.version)return!1;h5(a);h5(a);h5(a);return!0},l5=function(){M4.call(this)},SWa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Ij=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new J4(b,c,d,e.id,p.nodeValue,f||0<n,g.Df(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};Object.assign(r,l);SWa(a,b,c,d,e,!0,p,r,m)}}},m5=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},TWa=function(a,b,c,d){d=Object.assign({Et:0},d);
return new K4(a,b,c,"_"+L4++,d)},n5=function(a,b){g.H.call(this);
this.G=a;this.X=b;this.i=null;this.j=this.G.Vs()},ZWa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.X.L("enable_h5_ssdai_caption")&&b){var f=e,h=UWa(a,b,d),l=[];try{for(var m=g.q(h),n=m.next();!n.done;n=m.next()){var p=n.value,r=p.trackData,t=p.EH;l="string"!==typeof r?l.concat(VWa(a,c,r,t,f)):"WEBVTT"===r.substring(0,6)?l.concat(WWa(a,r,t)):l.concat(XWa(a,c,r,t))}var u=l}catch(x){g.S(x),a.clear(),u=[]}if(0!==u.length)return u}b=YWa(b);if(!b)return[];try{return"string"!==typeof b?VWa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?WWa(a,b,d):XWa(a,c,b,d)}catch(x){return g.S(x),a.clear(),[]}},
YWa=function(a){if("string"===typeof a||k5(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.Yz(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.Kz(a)},UWa=function(a,b,c){if("string"===typeof b||k5(b))return[{trackData:b,
EH:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Wpa(d);if(a.j&&e){var f=g.Ppa(e);e=e.i;f&&e&&a.j.vy(e,f)}f=g.gA(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.q(f.entries());for(e=f.next();!e.done;e=f.next()){var h=g.q(e.value);e=h.next().value;h=h.next().value;h=new Uint8Array(b,h.dataOffset,h.size-(h.dataOffset-h.offset));h=g.Kz(h);a.push({trackData:h,EH:c+1E3*e})}$Wa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},$Wa=function(a,
b,c){var d=g.Yz(a,0,1836476516),e=9E4;
d&&(e=g.Zz(d)||9E4);d=0;var f=g.gA(a,1836019558);f=g.q(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.q(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.Yz(a,l.dataOffset,1953653094))&&(l=g.Yz(a,l.dataOffset,1952867444))&&(l=g.eA(l)/e*1E3,0===h&&(d=l),b[h].EH=l-d+c||c*h*1E3)}},VWa=function(a,b,c,d,e){if(!k5(c))throw Error("Invalid binary caption track data");
a.i||(a.i=new j5(e,b));return a.i.j(c,d)},WWa=function(a,b,c){a.i||(a.i=new l5);
a=a.i.j(b,c);.01>Math.random()&&g.lx(Error("Deprecated subtitles format in web player: WebVTT"));return a},XWa=function(a,b,c,d){if("{"===c[0])try{return a.i||(a.i=new T4(aXa(b))),a.i.j(c,d)}catch(f){return g.S(f),[]}var e=g.V1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.i||(a.i=new N4(aXa(b),a.X)),a.i.j(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},aXa=function(a){var b=
{};
if(a=g.UE(a))b.lang=a,g.DSa.test(a)&&(b.Nf=1);return b},q5=function(a){g.oM.call(this,a);
var b=this;this.G=a;this.X=this.G.T();this.videoData=this.G.getVideoData();this.jb=this.G.bb();this.B={zd:{}};this.C={zd:{}};this.qa=[];this.N={};this.Ia={};this.Y=!1;this.ub=g.TF(this.videoData);this.Wa=g.iAa(this.videoData,this.G);this.tb=!!this.videoData.captionTracks.length;this.zb=!!this.videoData.Qb;this.La="3"===this.X.controlsType;this.j=this.I=this.J=this.Ha=this.Ya=null;this.Qa=new n5(this.G,this.X);this.i=null;this.oa=new g.hC(this);this.Ta=new g.W({D:"div",K:"ytp-caption-window-container",
V:{id:"ytp-caption-window-container"}});var c=null,d=g.fr("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Uq(d));this.storage=c;c=a.rd();this.fb=!(null===c||void 0===c||!c.jy());this.u=bXa(this);this.W=!this.u&&this.La&&this.fb&&this.Wa;g.J(this,this.Qa);this.u?this.ya=this.xa=null:(this.xa=new g.gq(this.eI,void 0,this),g.J(this,this.xa),this.ya=new g.K(this.rY,2E3,this),g.J(this,this.ya));g.J(this,this.oa);this.X.L("caption_window_container_killswitch")||g.aM(this.player,this.Ta.element,
4);g.J(this,this.Ta);this.u||this.oa.S(a,"resize",this.gI);(this.kb=!g.Hw()&&!this.G.isFullscreen()&&!this.u&&!this.W&&!this.X.L("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.oa.S(a,"resize",this.gW);this.oa.S(a,"onPlaybackAudioChange",this.oV);this.oa.S(a,g.gy("captions"),function(e){b.onCueRangeEnter(e)});
this.oa.S(a,g.hy("captions"),function(e){b.onCueRangeExit(e)});
o5(this,p5(this)||{})},eXa=function(a){if(1===a.X.Wa||1===a.videoData.qv||"alwayson"===g.DF(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().j;var c=a.X;if(g.lE(c)&&c.L("web_player_prioritize_caption_visibility_on")&&("ON"===b||"on"===g.DF(a.videoData,"yt:cc")))return!0;if(2===a.X.Wa){var d;g.pE(a.X)?d=cXa(a):d=dXa(a,"module-enabled");if(null!=d)return!!d}c=z4(a.player.getAudioTrack(),A4(a.X));d=g.DF(a.videoData,"yt:cc");if(void 0===r5(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===
d;return"ON"===b||"on"===g.DF(a.videoData,"yt:cc")},s5=function(a,b){if(a.i&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.j},r5=function(a){var b=void 0,c=g.Qu(g.Pu.getInstance(),65);
if(g.pE(a.X)&&null!=c){if(null!=cXa(a))return!1;b=!c}return b},fXa=function(a){var b;
a.ub?b=new G4(a.X,a.videoData,a.player.getAudioTrack(),a.player):a.Wa?b=new D4(a.videoData.i,a.player):a.tb?b=new g.sM(a.X,a.videoData,a.player.getAudioTrack()):b=new g.uM(a.X,a.videoData.Qb,a.videoData.videoId,g.Uua(a.videoData),a.videoData.uj);return b},u5=function(a,b){if(a.j){if(a.I&&a.I.B)return a.I.B;
b||(b=a.zb?!1:a.tb?!1:!0);b=g.pM(a.j.j,b);for(var c=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.DF(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.UE(b[e])===c[d])return b[e];return a.I&&a.I.u?a.I.u:(c=b.find(function(f){return f.isDefault}))?c:b[0]||t5(a)}return null},t5=function(a){return a.I&&a.I.i},v5=function(a){var b=t5(a);
return!!b&&a.i===b},gXa=function(a){var b=z4(a.player.getAudioTrack(),A4(a.X)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=u5(a,a.Y):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&s5(a)?c=t5(a):r5(a)||a.Y||eXa(a)?c=u5(a,a.Y):s5(a)&&(c=t5(a));if(a.u||a.W){var d=g.pM(a.j.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.Qh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.SE(f));h.setAttribute("srclang",g.UE(f));h.setAttribute("id",f.toString());a.W||h.setAttribute("src",a.j.jq(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.G.rd();c.Bv(b);c=c.Ge();
a.fb&&a.oa.S(c.textTracks,"change",a.GX)}else!a.i&&c&&w5(a,c),a.player.Oa("onCaptionsTrackListChanged"),a.player.Oa("onApiChange")},hXa=function(a,b){var c=a.G.rd().Ge().textTracks;
a=a.i.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},w5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Y=c,a.Y&&(g.pE(a.X)?x5(a,!!b):y5(a,"module-enabled",!!b)));a.i=b;s5(a)&&(a.i=t5(a));a.load()},iXa=function(a,b){a.X.L("caption_window_container_killswitch")?g.aM(a.player,b,4):a.Ta.element.appendChild(b)},jXa=function(a,b){var c=a.jb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?g.UE(a.i):null;d&&g.DSa.test(d)&&(b.params.Nf=1);d=a.jb.getPlayerSize();switch(null!=b.params.Et?b.params.Et:1<b.i.length?1:0){case 1:return new H4(b,a.B,a.C,c,d.width,d.height,a.X.experiments);case 2:return new I4(b,a.B,a.C,c,d.width,d.height,a.X.experiments);default:return new F4(b,a.B,a.C,c,d.width,d.height,a.X.experiments)}},o5=function(a,b,c){c=void 0===c?!1:c;
var d=z5.zd;a.B={};Object.assign(a.B,z5);a.B.zd={};Object.assign(a.B.zd,d);a.C={zd:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;R4.test(f);e.zd.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;R4.test(f);e.zd.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||z5.windowColor;R4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.zd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.zd.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Ij?3:d.bold?1:d.Ij?2:0);f=f.zd;switch(e){case 1:f.bold=!0;delete f.Ij;break;case 2:delete f.bold;f.Ij=!0;break;case 3:f.bold=!0;f.Ij=!0;break;default:delete f.bold,delete f.Ij}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.zd.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=z5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.zd.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.zd.fontFamily=f;a.loaded&&a.gI();c&&(a.X.L("web_player_local_storage_for_captions_setting_killswitch")?y5(a,"display-settings",b):g.Dx("yt-player-caption-display-settings",b,2592E3))},A5=function(a,b,c){b&&!a.J?(b=vWa({Nf:0,
lang:"fr"}),a.J=[b,new J4(b.start,b.end-b.start,0,b.id,null!==c&&void 0!==c?c:"Aper\u00e7u des sous-titres")],a.player.Ld(a.J)):!b&&a.J&&(kXa(a,a.J),a.J=null)},kXa=function(a,b){a.player.Lf(b);
g.yc(b,function(c){g.gc(this.qa,c)},a);
g.hq(a.xa)},dXa=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},y5=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},x5=function(a,b){a.G.isInline()||g.Dx("yt-player-sticky-caption",b,2592E3)},cXa=function(a){if(!a.G.isInline())return g.Ex("yt-player-sticky-caption")},p5=function(a){return a.X.L("web_player_local_storage_for_captions_setting_killswitch")?dXa(a,"display-settings"):g.Ex("yt-player-caption-display-settings")},bXa=function(a){var b=a.G.rd();
b=!(null===b||void 0===b||!b.iy());return a.La&&b&&!a.Wa};
g.wS.prototype.jw=g.da(34,function(a){var b=2;this.ya.has(a)?b=0:g.bGa(this,a)&&(b=1);return b});
g.bV.prototype.jw=g.da(33,function(a){return this.md.jw(a)});
g.wS.prototype.vy=g.da(32,function(a,b){this.Qa.set(a,b)});
g.bV.prototype.vy=g.da(31,function(a,b){this.md.vy(a,b)});
g.GM.prototype.Bs=g.da(30,function(){this.ra();for(var a=g.Eh(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Uh(a[b])});
g.dS.prototype.Bs=g.da(29,function(){this.ea.Bs()});
g.GM.prototype.jy=g.da(28,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.dS.prototype.jy=g.da(27,function(){return this.ea.jy()});
g.GM.prototype.iy=g.da(26,function(){return!!this.i.textTracks});
g.dS.prototype.iy=g.da(25,function(){return this.ea.iy()});
g.GM.prototype.Bv=g.da(24,function(a){this.ra();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.dS.prototype.Bv=g.da(23,function(a){this.ea.Bv(a)});
g.rM.prototype.TG=g.da(22,function(){return!1});
g.rM.prototype.Do=g.da(21,function(){});
g.sM.prototype.Do=g.da(20,function(a,b,c){var d=this;this.isDisposed();b=this.jq(a,b);this.Zm();this.i=g.Us(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.uM.prototype.Do=g.da(19,function(a,b,c){var d=this;this.isDisposed();b=this.jq(a,b);this.Zm();this.i=g.Us(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.MU.prototype.Aw=g.da(7,function(){return this.B});
g.QX.prototype.Aw=g.da(6,function(){var a;return(null===(a=g.cM(this))||void 0===a?void 0:a.Vs())||null});
g.UL.prototype.Vs=g.da(5,function(){return this.app.Aw()});
g.rX.prototype.Vs=g.da(4,function(){var a;return(null===(a=this.Va)||void 0===a?void 0:a.Aw())||null});
var gWa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",
az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bh:"Bhojpuri",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",
cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",
de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",
es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",
gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",
iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",
kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",
lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",
mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",
ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",
pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",
sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",
sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",swc:"Congo Swahili",
syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",
uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};B4.prototype.contains=function(a){a=g.sc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
B4.prototype.length=function(){return this.segments.length/2};
g.w(C4,g.H);g.k=C4.prototype;g.k.va=function(){g.H.prototype.va.call(this);this.u&&this.u.cancel()};
g.k.YA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.jd();var b=this.i;this.i=g.Vb(this.Y.pm(a).i);b!==this.i&&this.W&&this.W()};
g.k.reset=function(){this.B=new B4;this.I=-1;this.u&&(this.u.cancel(),this.u=null)};
g.k.MM=function(){var a;this.isDisposed();var b;if(b=null!=this.i)b=this.i,b=b.i.hn(b);if(b&&!this.u&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.Uu(b);if(this.X.L("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.Vs();if(c){var d=b.i[0].Na,e=c.Wk(b.i[0].B,d,b.i[0].i.info.id,3);if(e)if(c=c.jw(d),0===c)e&&(b.u=new g.wz(e));else if(2===c){this.J.start();eWa(this)&&this.seekTo(this.player.getCurrentTime());
return}}}b.i[0].duration?(this.B.contains(b.i[0].Na)||fWa(this,b),this.i=g.Vb(b.i)):!this.X.L("force_caption_seek_for_live_killswitch")&&eWa(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.k.ra=function(){};
g.w(D4,g.rM);g.k=D4.prototype;g.k.Do=function(a,b,c){var d=this;this.Zm();b=iWa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?jWa(this,b,"386"):jWa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.gAa(this.X);this.u=new C4(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.RB(b.info),function(){d.u&&d.u.reset();
d.C=!0})}};
g.k.TG=function(){var a=this.C;this.C=!1;return a};
g.k.At=function(a){var b=this.I?[new g.RE({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.RE({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?hWa(this,"386"):hWa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g.qM(this.j,c.value);a()};
g.k.Zm=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.jq=function(){return""};
var R4=/^#(?:[0-9a-f]{3}){1,2}$/i,lWa=/#(.)(.)(.)/,kWa=/^#(?:[0-9a-f]{3}){1,2}$/i;var nWa=["left","right","center","justify"];g.w(F4,g.W);g.k=F4.prototype;g.k.pR=function(a,b){var c=g.mn(this.element,this.element.parentElement);this.Ya=a-c.x;this.fb=b-c.y;g.N(this.element,"ytp-dragging")};
g.k.oR=function(a,b){var c=g.on(this.element);a=a-this.Ya-.02*this.playerWidth;var d=b-this.fb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.dh(e,0,2));var f=(d+c.height/2)/this.Ta*3;f=Math.floor(g.dh(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.dh(a,0,1);c=(d+f/2*c.height)/this.Ta;c=100*g.dh(c,0,1);this.j.params.ri=b;this.j.params.dk=c;this.j.params.jh=a;this.i.ri=b;this.i.dk=c;this.i.jh=a;this.Ha.ri=b;this.Ha.dk=c;this.Ha.jh=a;this.MO()};
g.k.nR=function(){g.zq(this.element,"ytp-dragging")};
g.k.MO=function(){this.fu(this.C)};
g.k.getType=function(){return this.type};
g.k.fu=function(a){var b=Math.min(this.CL(),this.maxWidth),c=this.BL(),d="";3===this.j.params.Nf&&(d="rotate(180deg)");g.cn(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.KD(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.jh+2;d=this.i.ri;switch(d){case 0:case 3:case 6:(b=this.i.zd.fontSizeIncrement)&&0<b&&2!==this.i.Nf&&3!==
this.i.Nf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.dk+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.cn(this.element,
a)};
g.k.KD=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.qa||this.C.length>b)b=0,this.qa=!1,this.C=[],this.I=this.ya=this.xa=null,g.Sh(this.B);for(;b<a.length;b++)rWa(this,a[b])};
g.k.CL=function(){return 0};
g.k.BL=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.w(G4,g.rM);G4.prototype.Do=function(a,b,c){cWa(this.videoData.videoId,a.vssId,c)};
G4.prototype.At=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.qM(this.j,c.value);a()};g.w(H4,F4);H4.prototype.KD=function(a){var b=this.j.i;F4.prototype.KD.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};Object.assign(d,c.i);Object.assign(d,lXa);var e=c.i;var f=d}rWa(this,c,d)}};
var lXa={aU:!0};g.w(I4,F4);g.k=I4.prototype;g.k.MO=function(){g.jq(this.Qa)};
g.k.YW=function(){g.zq(this.element,"ytp-rollup-mode");this.fu(this.ub,!0)};
g.k.BL=function(){return this.u?this.W:this.N};
g.k.CL=function(){return this.u?this.N:this.W};
g.k.fu=function(a,b){this.ub=a;if(this.j.params.Rm){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.jb=this.W;this.N=this.W=0;F4.prototype.fu.call(this,a);uWa(this,b)}F4.prototype.fu.call(this,a)};g.w(J4,g.ey);J4.prototype.toString=function(){return g.ey.prototype.toString.call(this)};g.w(K4,g.ey);K4.prototype.toString=function(){return g.ey.prototype.toString.call(this)};
var L4=0;g.w(M4,g.H);M4.prototype.j=function(){return[]};
M4.prototype.reset=function(){};g.w(N4,M4);N4.prototype.reset=function(){this.J={};this.u=this.i=null;this.I=!0};
N4.prototype.j=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=P4(a,"b");
null!=l&&(h.bold=l);l=P4(a,"i");null!=l&&(h.Ij=l);l=P4(a,"u");null!=l&&(h.underline=l);l=Q4(a,"et");null!=l&&(h.charEdgeStyle=l);l=Q4(a,"of");null!=l&&(h.offset=l);l=S4(a,"bc");null!=l&&(h.background=l);l=S4(a,"ec");null!=l&&(h.aE=l);l=S4(a,"fc");null!=l&&(h.color=l);l=Q4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=O4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=O4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=O4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=Q4(a,"rb");null!=l&&10!==l&&0!==
l&&(h.pe=10<l?l-1:l);a=Q4(a,"hg");null!=a&&(h.dM=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.W[c]=yWa(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=zWa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=AWa(this,a,b,!1);(a=this.J[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.J[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.C;h=
!!P4(a,"a");l=(O4(a,"t")||0)+l;var m=O4(a,"d")||5E3;h||(!this.I&&this.u&&this.u.windowId===f&&this.u.end>l&&(this.u.end=l),this.u&&"\n"===this.u.text&&(this.u.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var r=Array.from(a.childNodes);r.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var u=r[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.pens[u]:null)&&u.pe&&(1===u.pe?(u=r.slice(t,t+4),
4===u.length&&(x=xWa(l,m,f,h,n,u,this.pens),t+=3)):x=xWa(l,m,f,h,n,[y],this.pens)),!x){var z=y;x=l;y=m;u=f;var E=h,I=n,G=z.textContent?z.textContent:"",L=z.getAttribute("p");L=L?this.pens[L]:null;z=O4(z,"t")||0;x=new J4(x+z,y-z,I,u,G,E,L)}}else x=new J4(l,m,n,f,u.textContent||"",h,p);c.push(x);this.u=x}if(0<c.length)for(c[0].windowId===this.C&&(this.i=AWa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var mXa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(T4,M4);T4.prototype.reset=function(){this.u.clear()};
T4.prototype.j=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.Ij=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.aE=U4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=U4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=U4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.pe=10<h?h-1:h,f.bk=mXa.get(f.pe));e.hgHorizGroup&&(f.dM=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.C.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Et=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Nf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.NH=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=U4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.C.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.B.get(h)),void 0!==e.ahHorPos&&
(f.jh=e.ahHorPos),void 0!==e.apPoint&&(f.ri=e.apPoint),void 0!==e.avVerPos&&(f.dk=e.avVerPos),void 0!==e.ccCols&&(f.Dn=e.ccCols),void 0!==e.rcRows&&(f.Rm=e.rcRows),this.B.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=BWa(this,l,d,e,f),a.push(d),this.u.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+L4++,h=BWa(this,l,d,e,f),a.push(h),this.u.set(f,h));0===e&&(e=5E3);h=this.u.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.Et?h.params.Et:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.pe)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.i.get(z))&&z.pe&&2===z.pe?(z=p[t+2].pPenId,z=this.i.get(z),!z||!z.pe||3>z.pe?t=!1:(z=p[t+3].pPenId,t=(z=this.i.get(z))&&
z.pe&&2===z.pe?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var E=this.i.get(p[l+2].pPenId);u=wWa(u,x,z,t,E);m=new J4(d,e,n,f,u,m,y);l+=3}else m=new J4(d+x,e-x,n,h.id,u,m,y||r);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};W4.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
W4.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var CWa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];X4.prototype.set=function(a){this.type=a};
X4.prototype.get=function(){return this.type};
Y4.prototype.clear=function(){this.state=0};
Y4.prototype.update=function(){this.state=2===this.state?1:0};
Y4.prototype.isValid=function(){return 0!==this.state};
Y4.prototype.matches=function(a,b){return this.isValid()&&a===this.Mp&&b===this.zn};
HWa.prototype.reset=function(){this.timestamp=this.i=0};
Z4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
Z4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
Z4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.j=this.row=1};
var IWa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],JWa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],KWa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],LWa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];e5.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.j=this.I;this.B=this.J;this.i=this.j;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
V4.prototype.reset=function(a){this.C=a;this.j.clear();this.B=this.u;this.u.reset(a,0);this.I.reset(a,1)};QWa.prototype.C=function(){};g.w(g5,QWa);g5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+L4++;c=c/1E3-this.J;d=d/1E3-this.J;a=new K4(c,d-c,5,f,{textAlign:0,ri:0,jh:2.5*b,dk:5.33*a});e=new J4(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(j5,M4);j5.prototype.j=function(a){a=new g5(a,a.byteLength,this.u);if(RWa(a)){for(;a.i<a.j.byteLength;)for(0===a.version?a.B=i5(a)*(1E3/45):1===a.version&&(a.B=4294967296*i5(a)+i5(a)),a.I=h5(a);0<a.I;a.I--){var b=h5(a),c=h5(a),d=h5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.B,type:this.track,FK:c,GK:d,order:b.i.length}))}GWa(this.i,a);return a.u}return[]};
j5.prototype.reset=function(){this.i.clear()};g.w(l5,M4);
l5.prototype.j=function(a,b){var c=[];a=a.split(nXa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!oXa.test(e)){var h=B5.exec(e);if(h&&4<=h.length){var l=m5(h[1]),m=m5(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var r="";var t=null,u="";n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.dk=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.jh=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||r||(r="end");if(!t)switch(h.textAlign){case 0:h.jh=0;break;case 1:h.jh=100;break;case 2:h.jh=50}if(null!=h.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;h.ri=r}e=e.substring(B5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=TWa(l,m,5,u),m=new J4(l,m,5,f.id,h,!1,g.Df(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=h.split(pXa),1===r.length?(h=5,u=TWa(l,m,h,u)):(p=h=6,u=Object.assign({Dn:32},u),u=new K4(l,m,p,"_"+L4++,u)),c.push(u),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.V1("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,SWa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=m5(n)+f}B5.lastIndex=0}}return c};
var oXa=/^NOTE/,nXa=/(?:\r\n|\r|\n){2,}/,B5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),pXa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.kS.rA(l5,{j:"wvppt"});g.w(n5,g.H);n5.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
n5.prototype.reset=function(){this.i&&this.i.reset()};
n5.prototype.va=function(){g.H.prototype.va.call(this);this.clear()};var z5={windowColor:"#080808",windowOpacity:0,textAlign:2,ri:7,jh:50,dk:100,zd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(q5,g.oM);g.k=q5.prototype;g.k.va=function(){if(this.u||this.W){var a=this.G.rd();a&&!a.isDisposed()&&a.Bs()}else A5(this,!1);g.oM.prototype.va.call(this)};
g.k.Zq=function(){if(this.La)return this.u||this.W;var a=z4(this.player.getAudioTrack(),A4(this.X));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?s5(this):r5(this)||s5(this)?!0:eXa(this)};
g.k.load=function(){var a=this;g.oM.prototype.load.call(this);var b=!this.X.L("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.j?(this.i&&(this.Qa.clear(),this.u?hXa(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.Do(this.i,"json3",function(c,d,e,f){c&&(a.j.TG()&&(a.qa=[],a.G.df("captions"),g.hq(a.xa),a.Qa.reset()),c=ZWa(a.Qa,c,d,e,f),a.player.Ld(c,void 0,a.Wa),!a.Y||a.W||v5(a)||g.cE(a.X)||g.WD(a.X)||(g.kq(a.ya),c=vWa({ri:0,jh:5,dk:5,Rm:2,textAlign:0,
Nf:0,lang:"fr"}),a.Ha=[c],d=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],a.Ya||(e=new g.RJ(g.kK()),g.J(a,e),a.Ya=e.element),e=c.end-c.start,(f=g.SE(a.i))&&a.Ha.push(new J4(c.start,e,0,c.id,f)),a.Ha.push(new J4(c.start,e,0,c.id,d[0]),new J4(c.start,e,0,c.id,a.Ya,!0),new J4(c.start,e,0,c.id,d[1],!0)),a.player.Ld(a.Ha),g.iq(a.ya)),!a.Y||a.W||v5(a)||(g.pE(a.X)?x5(a,!0):y5(a,"module-enabled",!0),a.I&&(a.I.B=a.i),a.player.vr()),a.Y=!1)}),!b||this.u||this.W||v5(this)||this.player.Oa("captionschanged",
g.TE(this.i))),b||(this.i&&!v5(this)?this.player.Oa("captionschanged",g.TE(this.i)):this.player.Oa("onCaptionsTrackListChanged"))):(this.j=fXa(this),g.J(this,this.j),this.j.At(function(){gXa(a)}))};
g.k.unload=function(){this.u&&this.i?hXa(this,!1):(this.ya&&g.kq(this.ya),this.player.df("captions"),this.qa=[],this.j&&this.j.Zm(),this.Qa.clear(),this.J&&this.player.Ld(this.J),this.gI());g.oM.prototype.unload.call(this);this.player.vr();this.player.Oa("captionschanged",{})};
g.k.create=function(){this.Zq()&&this.load()};
g.k.GX=function(){for(var a=this.G.rd().Ge().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.pM(this.j.j,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&w5(this,b,!0)};
g.k.pZ=function(){!this.i&&this.u||this.unload()};
g.k.onCueRangeEnter=function(a){this.qa.push(a);g.hq(this.xa)};
g.k.onCueRangeExit=function(a){g.gc(this.qa,a);this.j instanceof D4&&this.j.I&&this.player.Lf([a]);g.hq(this.xa)};
g.k.kY=function(a){if(a instanceof K4){var b=this.N[a.id];b&&b.j!==a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=jXa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.Ia[b]||(this.Ia[b]=[]),this.Ia[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Ta.element.id};
g.k.rY=function(){kXa(this,this.Ha);this.Ha=null};
g.k.eI=function(){var a=this;if(!this.kb||!this.u){this.xa.stop();g.Ef(this.Ia);this.qa.sort(g.fy);var b=this.qa;if(this.J){var c=g.Mo(b,function(d){return-1===this.J.indexOf(d)},this);
c.length&&(b=c)}g.yc(b,this.kY,this);g.qf(this.N,function(d,e){a.Ia[e]?(d.element.parentNode||(d instanceof I4||d instanceof H4||g.tf(a.N,function(f,h){h!==e&&f.j.params.ri===d.j.params.ri&&f.j.params.jh===d.j.params.jh&&f.j.params.dk===d.j.params.dk&&(f.dispose(),delete a.N[h]);return h===e},a),iXa(a,d.element)),d.fu(a.Ia[e])):(d.dispose(),delete a.N[e])},this)}};
g.k.vY=function(){o5(this,{},!0);this.X.L("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Oa("captionssettingschanged")};
g.k.vT=function(){var a=z5.zd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ij?3:a.bold?1:a.Ij?2:0,textOpacity:a.textOpacity,windowColor:z5.windowColor,windowOpacity:z5.windowOpacity};var b=p5(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.KP=function(a,b){var c={};Object.assign(c,p5(this));Object.assign(c,a);o5(this,c,b);this.player.Oa("captionssettingschanged")};
g.k.gI=function(){!this.u&&this.loaded&&(g.qf(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.eI())};
g.k.sf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.dh(b,-2,4);this.KP({fontSizeIncrement:c});return c;case "reload":b&&!this.u&&w5(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.X.u&&(g.pE(this.X)?x5(this,!!b):y5(this,"module-enabled",!!b));break;case "track":if(!this.j)return{};if(b){if(this.u)break;if(!g.Qa(b))break;if(g.Df(b)){w5(this,null,!0);break}a=g.pM(this.j.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?bWa(e,b.translationLanguage):e)}!c||c===this.i&&this.loaded||(b=g.Tra(),a=g.UE(c),b.length&&a===b[b.length-1]||(b.push(a),g.Dx("yt-player-caption-language-preferences",b)),w5(this,c,!0))}else return this.loaded&&this.i&&!v5(this)?g.TE(this.i):{};return"";case "tracklist":return this.j?g.vn(g.pM(this.j.j,!(!b||!b.includeAsr)),function(f){return g.TE(f)}):[];
case "translationLanguages":return this.j?this.j.B.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.u||void 0===b||A5(this,!!b);break;case "sampleSubtitlesCustomized":this.u||A5(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.u&&a.push("stickyLoading");return a};
g.k.aF=function(){var a=this.i;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.X.L("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.UE(a));return{cc:b}}return{}};
g.k.eZ=function(){this.loaded&&this.i&&!v5(this)?(g.pE(this.X)?x5(this,!1):y5(this,"module-enabled",!1),this.unload(),s5(this,!0)&&w5(this,t5(this),!1)):this.sP()};
g.k.sP=function(){this.loaded&&this.i&&!v5(this)||w5(this,v5(this)||!this.i?u5(this,!0):this.i,!0)};
g.k.oV=function(){var a=v5(this);s5(this,a)?w5(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Zq()&&(a?w5(this,u5(this),!1):this.load()))};
g.k.gW=function(){var a=this.G.rd();a&&!a.isDisposed()&&a.Bs();this.G.isFullscreen()?(this.u=this.La=!0,this.loaded&&gXa(this)):(this.La="3"===this.X.controlsType,this.u=bXa(this));w5(this,this.i)};
g.kS.rA(q5,{eI:"smucd"});g.nM("captions",q5);})(_yt_player);
